### ISSUE TITLE
Double loading?

### ISSUE THREAD

**Issue by cycle4passion** [Julien-R44/unocss-preset-flowbite#2]
Sveltekit-TS project. I have added unoCSS and it is functional. Once I add your preset as per instructions everything works until I import a Flowbite component. commenting out your suggest changes in vite.config gets it functional again.

```js
[ERROR] The symbol "click_handler" has already been declared

    node_modules/.pnpm/flowbite-svelte@0.29.2/node_modules/flowbite-svelte/dropdowns/DropdownItem.svelte:344:10:
      344 │   function click_handler(event) {
          ╵            ~~~~~~~~~~~~~

  The symbol "click_handler" was originally declared here:

    node_modules/.pnpm/flowbite-svelte@0.29.2/node_modules/flowbite-svelte/dropdowns/DropdownItem.svelte:312:10:
      312 │   function click_handler(event) {
          ╵            ~~~~~~~~~~~~~
....more
```

Any help would be appreciated.  

[Stackblitz](https://stackblitz.com/github/cycle4passion/sk-uno-fbsv?file=vite.config.js)

**Comment by Julien-R44** [comment]
I don't think there is any connection.
I tried to uncomment the presetFlowbite in your stackblitz and the errors are still there: 

https://stackblitz.com/edit/github-w8xfwt-rnennf?file=vite.config.js

Feel free to reopen the issue if it turns out that the problem is coming from this library. ( But I really don't think so )

**Comment by cycle4passion** [comment]
Thanks for looking, I found that it is an identified Sveltekit issue - https://github.com/sveltejs/kit/issues/8218
