### ISSUE TITLE
What is not included

### ISSUE THREAD

**Issue by joshua1** [Julien-R44/unocss-preset-flowbite#3]
Hi @Julien-R44  I came across your project while trying to use flowbite with unocss. I would like to know what is not included in this preset that is available on flowbite. It would have been nice to have everything included , and a subset (for your use case) with just the bit you needed

**Comment by Julien-R44** [comment]
Hey, actually this project is just an adaptation of the tailwind flowbite plugin but for UnoCSS.

This plugin only adds styling for the components offered by Flowbite. Basically I only integrated the styling for some components in my plugin. So I recommend you to just use the plugin and if you ever find that one of your components is not displaying properly, then the problem is probably with my plugin. And in that case I invite you to reopen an issue specifying the problematic component so that I can add the corresponding styling to it.

The purpose of this plugin is not to include only a subset, it's just that I integrated only what I needed at a given time. I'm quite open to including the whole thing.

**Comment by shiftlabs1** [comment]
Thanks @Julien-R44 . I will do that open

**Comment by joshua1** [comment]
> 

WOuld be helpful if you can include the whole thing. Not everyone is able to tell what is missing . There are no other plugins for unocss out there catering in any part to flowbite , other than this . If i had a better understanding of what the plugins entail i will extend this with the missing bit. I guess , looking at the flowbite plugin implementation for tailwindcss will be a good place to start

**Comment by Julien-R44** [comment]
I'm not sure what the problem is. You will be able to tell what is missing by using it. If you are missing something, just open another issue
